routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UsersController@index')->name('home');
Route::resource('photos', 'PhotosController')->except(['edit', 'update']);
Route::resource('users', 'UsersController')->only(['index', 'show']);
Route::resource('comments', 'CommentsController')->only(['store', 'edit', 'update', 'destroy']);
Route::resource('subscriptions', 'SubscriptionsController')->only(['store', 'destroy']);
Route::resource('likes', 'LikesController')->only(['store', 'destroy']);


Auth::routes();

app/User.php
<?php

namespace App;

use Orchid\Platform\Models\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'surname',
        'patronymic',
        'email',
        'password',
        'last_login',
        'permissions',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'permissions',
        'uses_two_factor_auth',
        'two_factor_secret_code',
        'two_factor_recovery_code',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'permissions'          => 'array',
        'email_verified_at'    => 'datetime',
        'last_login'           => 'datetime',
        'uses_two_factor_auth' => 'boolean',
    ];

    /**
     * The attributes for which you can use filters in url.
     *
     * @var array
     */
    protected $allowedFilters = [
        'id',
        'name',
        'email',
        'permissions',
    ];

    /**
     * The attributes for which can use sort in url.
     *
     * @var array
     */
    protected $allowedSorts = [
        'id',
        'name',
        'email',
        'last_login',
        'updated_at',
        'created_at',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function photos()
    {
        return $this->hasMany(Photo::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function subscribers()
    {
        return $this->belongsToMany(
            self::class,
            'subscriptions',
            'user_id',
            'subscriber_id'
        )->withTimestamps();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function subscriptions()
    {
        return $this->belongsToMany(
            self::class,
            'subscriptions',
            'subscriber_id',
            'user_id'
        )->withTimestamps();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function likes()
    {
        return $this->hasMany(Like::class);
    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('users.index');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('users.show', compact('user'));
    }
}

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="text-right">
        <h2>{{Auth::user()->name}} {{Auth::user()->patronymic}} {{Auth::user()->surname}}</h2>
        <p><a href="{{route('photos.create')}}">Добавить фото</a></p>
    </div>
    <p class="mt-3 h4">Ваши фотографии:</p>

    <div>
        @foreach(Auth::user()->photos as $photo)
            <a href="{{route('photos.show', ['photo' => $photo])}}"><img src="{{asset('storage/' . $photo->photo)}}" alt="{{$photo->photo}}" class="img-thumbnail" style="width: 300px; height: 250px"></a>
        @endforeach
    </div>

@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="text-right">
        <h2>{{$user->name}} {{$user->patronymic}} {{$user->surname}}</h2>

        @can('create', $user)
            <form method="post" action="{{route('subscriptions.store')}}">
                @csrf
                <input type="hidden" id="user_id" name="user_id" value="{{$user->id}}">
                <button type="submit" class="btn btn-primary small">Подписаться</button>
            </form>
        @endcan

        @can('delete', $user)
        <form method="post" action="{{route('subscriptions.destroy', ['subscription' => $user])}}">
            @method('delete')
            @csrf
            <button type="submit" class="btn btn-danger small">Отписаться</button>
        </form>
        @endcan
    </div>

    <div>
        <h3>Все фотографии</h3>
        <hr>
        <div class="row row-cols-1 row-cols-md-3 mt-4">
            @foreach($user->photos as $photo)
                <div>
                    <a href="{{route('photos.show', ['photo' => $photo])}}">
                        <img src="{{asset('storage/' . $photo->photo)}}" alt="{{$photo->photo}}" class="mb-5 mr-5" style="width: 300px; height: 250px">
                    </a>

                    <div>
                        <form action="{{route('likes.store')}}" method="post" style="margin-top: -30px">
                            @csrf
                            <input type="hidden" id="photo_id" name="photo_id" value="{{$photo->id}}">
                            <button type="submit" class="border-0" style="font-size:20px;"><i class='far fa-thumbs-up'></i></button>
                        </form>
                    </div>

                    <div>
                        @foreach($photo->likes as $photo_like)
                            @can('delete', $photo_like)
                                <form action="{{route('likes.destroy', ['like' => $photo_like])}}" method="post" style="margin-top: -34px">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="border-0" style="font-size:20px; "><i class='fas fa-thumbs-up'></i></button>
                                </form>
                            @endcan
                        @endforeach
                    </div>
                    <p>{{$photo->likes->count()}}</p>
                    <hr>
                </div>
            @endforeach
        </div>
    </div>

@endsection