routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UsersController@index')->name('home');
Route::resource('photos', 'PhotosController')->except(['edit', 'update']);
Route::resource('users', 'UsersController')->only(['index', 'show']);
Route::resource('comments', 'CommentsController')->only(['store', 'edit', 'update', 'destroy']);
Route::resource('subscriptions', 'SubscriptionsController')->only(['store', 'destroy']);
Route::resource('likes', 'LikesController')->only(['store', 'destroy']);


Auth::routes();

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $fillable = [
        'photo',
        'description',
        'user_id'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function likes()
    {
        return $this->hasMany(Like::class);
    }
}

app/Http/Controllers/PhotosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PhotoRequest;
use App\Photo;
use Illuminate\Http\Request;

class PhotosController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $photos = Photo::Paginate(12);
        return view('photos.index', compact('photos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('photos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PhotoRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(PhotoRequest $request)
    {
        $photo = new Photo($request->all());
        $photo['user_id'] = $request->user()->id;
        $file = $request->file('photo');
        $photo['photo'] = $file->store('photos', 'public');
        $photo->save();

        return redirect(route('users.index'))->with('status', 'Фотография добавлена');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $photo = Photo::findOrFail($id);

        $comments_count = 0;
        foreach ($photo->comments as $comment) {
            if ($comment->is_active) {
                $comments_count = $comments_count + 1;
            }
        }

        return view('photos.show', compact('photo', 'comments_count'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy($id)
    {
        $photo = Photo::findOrFail($id);
        $this->authorize('delete', $photo);
        $photo->delete();
        return redirect(route('users.index'))->with('status', 'Фотография удалена');
    }
}

resources/views/photos/create.blade.php
@extends('layouts.app')

@section('content')

    <h1>Добавить фотографию</h1>

    <form method="post" action="{{route('photos.store')}}" class="w-50" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="photo">Фотография</label>
            <input type="file" class="form-control-file @error('photo') is-invalid @enderror" id="photo" name="photo">
            @error('photo')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="description">Описание фотографии</label>
            <textarea class="form-control @error('description') is-invalid @enderror" id="description" rows="3" name="description"></textarea>
            <small class="form-text text-muted">
                *Заполнять не обязательно.
            </small>
            @error('description')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>

    <div class="mt-3 mb-3">
        <a href="{{route('users.index')}}">Назад</a>
    </div>

@endSection

resources/views/photos/index.blade.php
@extends('layouts.app')

@section('content')

    <h2 class="text-center">Лента</h2>

    <div class="row row-cols-1 row-cols-md-3 mt-4">
        @foreach($photos as $photo)
            <div>
                <p>Автор: <a href="{{route('users.show', ['user' => $photo->user->id])}}">{{$photo->user->name}} {{$photo->user->surname}}</a></p>
                <a href="{{route('photos.show', ['photo' => $photo])}}">
                    <img src="{{asset('storage/' . $photo->photo)}}" alt="{{$photo->photo}}" class="mb-5" style="width: 300px; height: 250px">
                </a>

                <div>
                    <form action="{{route('likes.store')}}" method="post" style="margin-top: -30px">
                        @csrf
                        <input type="hidden" id="photo_id" name="photo_id" value="{{$photo->id}}">
                        <button type="submit" class="border-0" style="font-size:20px;"><i class='far fa-thumbs-up'></i></button>
                    </form>
                </div>

                <div>
                    @foreach($photo->likes as $photo_like)
                        @can('delete', $photo_like)
                        <form action="{{route('likes.destroy', ['like' => $photo_like])}}" method="post" style="margin-top: -34px">
                            @method('delete')
                            @csrf
                            <button type="submit" class="border-0" style="font-size:20px; "><i class='fas fa-thumbs-up'></i></button>
                        </form>
                        @endcan
                    @endforeach

                </div>
                <p>{{$photo->likes->count()}}</p>
                <hr>
            </div>
        @endforeach
    </div>

    <div class="row p-5">
        <div class="col-12">
            {{ $photos->links() }}
        </div>
    </div>

@endsection

resources/views/photos/show.blade.php
@extends('layouts.app')

@section('content')

    <p class="card-text h4">Автор: <a href="{{route('users.show', ['user' => $photo->user])}}">{{$photo->user->name}} {{$photo->user->surname}}</a></p>

    <div class="card" style="width: 40rem;">
        <img src="{{asset('storage/' . $photo->photo)}}" alt="{{$photo->photo}}" class="card-img-top" style="height: 500px">
        <div class="card-body text-right">
            <p class="card-text">{{$photo->description}}</p>
            <p class="card-text text-right"><small class="text-muted">{{$photo->created_at->diffForHumans()}}</small></p>
            @can('delete', $photo)
            <form class="mt-3" method="post" action="{{route('photos.destroy', ['photo' => $photo])}}">
                @method('delete')
                @csrf
                <button type="submit" class="btn btn-outline-danger btn-sm">Удалить</button>
            </form>
            @endcan
            <form action="{{route('likes.store')}}" method="post">
                @csrf
                <input type="hidden" id="photo_id" name="photo_id" value="{{$photo->id}}">
                <button type="submit" class="border-0" style="font-size:20px;"><i class='far fa-thumbs-up'></i></button>
            </form>
            <div>
                @foreach($photo->likes as $photo_like)
                    @can('delete', $photo_like)
                        <form action="{{route('likes.destroy', ['like' => $photo_like])}}" method="post" style="margin-top: -34px">
                            @method('delete')
                            @csrf
                            <button type="submit" class="border-0" style="font-size:20px; "><i class='fas fa-thumbs-up'></i></button>
                        </form>
                    @endcan
                @endforeach

            </div>
            <p>{{$photo->likes->count()}}</p>
        </div>
    </div>

    <div>
        <button class="show-comments-btn btn btn-info mt-4" type="button" data-toggle="collapse"
                data-target="#comments-block">Комментарии: <span class="comments-number">{{$comments_count}}</span></button>
        <div id="comments-block" class=" collapse multi-collapse mt-5">
            @foreach($photo->comments as $comment)
                @can('show', $comment)
                <div class="card mb-3 w-50">
                    <h5 class="card-header">{{$comment->user->surname}} {{$comment->user->name}}</h5>
                    <div class="card-body">
                        <p class="card-text">{{$comment->body}}</p>
                        <p class="card-text text-right"><small class="text-muted">{{$comment->created_at->diffForHumans()}}</small></p>
                            <hr>
                            <div>
                                @can('edit', $comment)
                                <p><a href="{{route('comments.edit', ['comment' => $comment])}}">Изменить комментарий</a></p>
                                @endcan
                                @can('delete', $comment)
                                <form class="mt-3" method="post" action="{{route('comments.destroy', ['comment' => $comment])}}">
                                    @method('delete')
                                    @csrf
                                    <input type="hidden" id="photo_id" name="photo_id" value="{{$photo->id}}">
                                    <button type="submit" class="btn btn-outline-danger btn-sm">Удалить</button>
                                </form>
                                @endcan
                            </div>
                    </div>
                </div>
                @endcan
            @endforeach
        </div>
    </div>

    @can('showCommentForm', $photo)
    <form method="post" action="{{route('comments.store')}}" class="w-25 mt-5 mb-5">
        @csrf
        <input type="hidden" id="photo_id" name="photo_id" value="{{$photo->id}}">
        <div class="form-group">
            <label for="body">Комментарий:</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body" rows="3"></textarea>
            @error('body')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>
        <button type="submit" class="btn btn-success">Добавить комментарий</button>
    </form>
    @endcan

@endsection